---
title: "finalgraphs_rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
#load required packages
library(tidyr)
library(ggplot2)
library(magrittr)
library(reshape2)
library(lubridate)
library(dplyr)
library(survival)
install.packages("survminer")
library("survminer")
```

```{r}
#load and view data
survivorship <- read.csv('2019_PR_totalsurvivorship.csv')
View(survivorship)
```

```{r}
#load and view survivorship percent data
survivorship_percents <- read.csv('2019_PR_survivorshippercents.csv')
View(survivorship_percents)
```

```{r}
#box plot of survivorship percents only including cage and known field 
df <- survivorship_percents_mario_known
b1 <- ggplot(df, aes(x = treatment, y = percent)) +
  geom_boxplot() +
  geom_jitter()
b1 <- b1 + scale_x_discrete(name = "Fragment Location") + scale_y_continuous(name = "Percent Survivorship")
b1
```

```{r}
#load and view survivorship percent data broken down by acclimation treatment
survivorship_percents_acc_known <- read.csv('2019_PR_survivorship_acc_known.csv')
View(survivorship_percents_acc_known)
```

```{r}
#make acclimation variable a factor
survivorship_percents_acc_known$acclimation <- as.factor(survivorship_percents_acc_known$acclimation)
```

```{r}
#load and view field survivorship percent data broken down by acclimation treatment
survivorship_percents_acc_field <- read.csv('2019_PR_survivorship_acc_field.csv')
View(survivorship_percents_acc_field)
```

```{r}
#make acclimation variable a factor
survivorship_percents_acc_field$acclimation <- as.factor(survivorship_percents_acc_field$acclimation)
```

```{r}
#box plot comparing field survivorship over acclimation types
df <- survivorship_percents_acc_field
b4 <- ggplot(df, aes(x = acclimation, y = percent)) +
  geom_boxplot() +
  geom_jitter(aes(color = location))
b4 <- b4 + scale_x_discrete(name = "Acclimation Treatment") + scale_y_continuous(name = "Survivorship Percent")
b4 <- b4 + theme(legend.position = "none")
b4
```

```{r}
#box plot comparing field survivorship over acclimation types
df <- survivorship_percents_acc_field
b5 <- ggplot(df, aes(x = genotype, y = percent)) +
  geom_boxplot() +
  geom_jitter(aes(color = genotype))
b5 <- b5 + scale_x_discrete(name = "Genotype") + scale_y_continuous(name = "Survivorship Percent") + theme(legend.position = "none")
b5 
```

```{r}
#load survivorship curve data 
survivorship_curves <- read.csv('2019_PR_survivorshipcurves.csv')
View(survivorship_curves)
```

```{r}
#create new data frame with only field survivorship
#add cage percents
survivorship_curves_field <- subset(survivorship_curves, location == "field", select = c("location","proportion","days","genotype"))
View(survivorship_curves_field)
```

```{r}
#survivorship curve of all genotypes after outplanting
df <- survivorship_curves_field
l2 <- ggplot(df, aes(x = days, y = proportion, group = genotype, color = genotype)) +
  geom_line() +
  ylim(0, 1.0)
l2 <- l2 + scale_x_continuous(name = "Time (days)") + scale_y_continuous(name = "Survival")
l2
```

```{r}
#load average survivorship curve data 
survivorship_curves_avg <- read.csv('2019_PR_survivorshipcurves_avg.csv')
View(survivorship_curves_avg)
```

```{r}
#line graph of average survivorship data, compared between cage and field
df <- survivorship_curves_avg
l3 <- ggplot(df, aes(x = days, y = proportion, group = location, color = location)) +
  geom_line() +
  ylim(0,1.0)
l3 <- l3 + scale_x_continuous(name = "Time (days)") + scale_y_continuous(name = "Survival")
l3
```

```{r}
#load survminer formatted field data
survminer_field <- read.csv("2019_PR_survminer_field.csv")
View(survminer_field)
```

```{r}
#reformat all dates to POSIXt format using lubridate and delete old columns
survminer_field$ymd.planted=mdy(survminer_field$date.planted)
survminer_field$ymd.mortality=mdy(survminer_field$date.of.mortality)
survminer_field <- select(survminer_field, -date.planted, -date.of.mortality)
```

```{r}
#calculate number of days between planting and mortality 
survminer_field$days.alive <- difftime(survminer_field$ymd.mortality ,survminer_field$ymd.planted , units = c("days"))
```

```{r}
#create a survival object
Surv(survminer_field$days.alive, survminer_field$censored)[1:10]
```

```{r}
#create a survfit object using the Kaplan-Meier method
surv_object <- Surv(survminer_field$days.alive, survminer_field$censored)
surv_object
```

```{r}
#fit Kaplan-Meier curves
fit1 <- survfit(surv_object ~ 1, data = survminer_field)
fit1
```

```{r}
#Kaplan-Meier plot: method 2
s2 <- ggsurvplot(
  fit = survfit(surv_object ~ 1, data = survminer_field),
  xlab = "Time (days)",
  ylab = "Overall survival probability")
s2
```

```{r}
#Kaplan-Meier field data plots separated by genotype
fit2 <- survfit(surv_object ~ genotype, data = survminer_field)
s3 <- ggsurvplot(fit2, data = survminer_field, pval = TRUE)
s3
```

```{r}
#Kaplan-Meier field data plots separated by genotype
fit3 <- survfit(surv_object ~ acclimation, data = survminer_field)
s4 <- ggsurvplot(fit3, data = survminer_field, pval = TRUE)
s4
```

```{r}
#load survminer formatted cage data
survminer_cage <- read.csv("2019_PR_survminer_cage.csv")
View(survminer_cage)
```

```{r}
#reformat all dates to POSIXt format using lubridate and delete old columns
survminer_cage$ymd.cage=mdy(survminer_cage$date.put.in.cage)
survminer_cage$ymd.end=mdy(survminer_cage$date.sampled.or.planted)
survminer_cage <- select(survminer_cage, -date.put.in.cage, -date.sampled.or.planted)
```

```{r}
#calculate number of days between put in the cage and being taken out
survminer_cage$days.alive <- difftime(survminer_cage$ymd.end ,survminer_cage$ymd.cage , units = c("days"))
```

```{r}
#create a survfit object using the Kaplan-Meier method
surv_object2 <- Surv(survminer_cage$days.alive, survminer_cage$censored)
surv_object2
```

```{r}
#Kaplan-Meier plot of total cage data
s5 <- ggsurvplot(
  fit = survfit(surv_object2 ~ 1, data = survminer_cage),
  xlab = "Days",
  ylab = "Overall survival probability")
s5
```

```{r}
#Kaplan-Meier cage data plots separated by genotype
fit4 <- survfit(surv_object2 ~ genotype, data = survminer_cage)
s6 <- ggsurvplot(fit4, data = survminer_cage, pval = TRUE)
s6
```

```{r}
#load total survminer data
survminer_all <- read.csv("2019_PR_survminer_all.csv")
View(survminer_all)
```

```{r}
#create a survfit object using the Kaplan-Meier method
surv_object3 <- Surv(survminer_all$days.alive, survminer_all$censored)
surv_object3
```

```{r}
#Kaplan-Meier total data plots separated by genotype
fit5 <- survfit(surv_object3 ~ location, data = survminer_all)
s7 <- ggsurvplot(fit5, data = survminer_all, pval = TRUE)
s7
```

```{r}
#Kaplan-Meier total data plots separated by genotype
fit6 <- survfit(surv_object3 ~ genotype, data = survminer_all)
s8 <- ggsurvplot(fit6, data = survminer_all, pval = TRUE)
s8
```























.